events { worker_connections 1024; }
http {
    upstream spring_cluster {
        server app-small-1:8080;
        server app-small-2:8080;
        server app-small-3:8080;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://spring_cluster;
        }
    }
}